language: node_js
node_js: 
- node
before_install: cd WebClient
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
before_script: yarn
script: yarn test:coverage
cache:
  yarn: true
  directories: WebClient/node_modules